/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void lcd_show_page(char* text, int page);
void delay_ms(volatile uint32_t ms);

int main(void)
{
    lcd_init();

    char* message = "Dies ist eine lange Nachricht fuer das LCD 1602A, die komplett durchscrollen soll!";
    int len = strlen(message);

    while(1)
    {
        for(int offset=0; offset<len; offset++)
        {
            lcd_show_window(message, offset);
            delay_ms(100);  // Geschwindigkeit einstellen
        }
    }
}

// Scroll function flüssig
void lcd_show_window(char* text, int offset)
{
    if (!text) return;

    lcd_clear();
    delay_ms(2);

    int len = strlen(text);

    // 1. Zeile
    lcd_put_cur(0,0);
    for(int i=0; i<16; i++) {
        char c = text[(offset + i) % len];
        lcd_send_data(c);
    }

    // 2. Zeile
    lcd_put_cur(1,0);
    for(int i=16; i<32; i++) {
        char c = text[(offset + i) % len];
        lcd_send_data(c);
    }
}

void delay_ms(volatile uint32_t ms)
{
    for(volatile uint32_t i=0; i<ms*4000;i++);
}

/*void lcd_scrollText(char *text)
{
	int len = strlen(text);
	for(int i=0; i<len; i++)
	{
		lcd_clear();
		lcd_put_cur(0,0);
		for(int j=0; j<16 && i+j<len; j++)
		{
			lcd_send_string(&text[i+j]);
		}
	}
}
*/

